### PR TITLE
(GH-11) Allow passing of ViewBag Dictionary

### LINKED ISSUE #11: Allow passing of Dictionary for ViewBag
Rather than only using an Action, allow a populated Dictionary<string, object> to be passed in instead.

### PR DESCRIPTION
**Pull request by gep13**
Rather than expecting a ViewBag to be populated using an Action, allow
passing in a populated Dictionary<string, object> for the ViewBag.

Fixes #11

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 with this change, all unit tests in Cake.Issues.Reporting.Generic now pass.  There were some additional changes that need to be made over there as well, but this change would be required.

What are your thoughts on pulling this in?

**Comment by gep13** [comment]
We discussed the contents of this PR at length on tonights stream, if you want to review what was discussed, then please feel free 😄

**Comment by bjorkstromm** [comment]
@gep13 thank you for your contribution. Your changes have been merged!

**Comment by gep13** [comment]
@mholo65 woot!  Thanks for merging this!

**Pull request merged**
