### PR TITLE
(GH-16) Updated to Cake.Recipe 2.0.0

### LINKED ISSUE #16: Update to Cake.Recipe 2.0.0
Instructions here:

https://cake-contrib.github.io/Cake.Recipe/docs/upgrading/1.x-to-2.x

### PR DESCRIPTION
**Pull request by gep13**
- Switch to Cake.Tool
- Enable deterministic builds
- Pin to Cake 0.38.4
- Add GitHub Action build

Let me know if you have any questions.

Fixes #16

### CODE REVIEW

**Comment by gep13** [comment]
I am not entirely sure why the AppVeyor build failed.

**Comment by bjorkstromm** [comment]
> 
> 
> I am not entirely sure why the AppVeyor build failed.

`global.json` includes a SDK which is not installed on AppVeyor agent. Try making it little less strict, like [this](https://github.com/mholo65/depends/blob/master/global.json)

**Comment by gep13** [comment]
@mholo65 success!

**Review by bjorkstromm — APPROVED** [review]
LGTM! Thanks!

**Comment by bjorkstromm** [comment]
Thanks! I should now skip AppVeyor and move to GH actions.

**Comment by gep13** [comment]
>@mholo65 said...
Thanks! I should now skip AppVeyor and move to GH actions.

That is possible, needs a couple of other parameters sent into Cake.Recipe though.

I can take care of that if you want.

**Comment by bjorkstromm** [comment]
Sure! Go nuts! IIRC, you should have admin rights also, so feel free to also configure CI check on PR.

**Pull request merged**
